config/routes.rb
Rails.application.routes.draw do
	root 'pages#index'

	get '/posts', to: 'pages#posts', as: 'posts'
	get '/post/:id', to: 'pages#post', as: 'post'

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	get '/admin', to: 'admin#index'
	namespace :admin do
		resources :posts
		resources :categories
		resources :users
		resources :privileges
		resources :comments
	end

end

app/models/admin/comment.rb
class Admin::Comment < ActiveRecord::Base
	# validations
	validates :Text, length: {minimum: 60}      # set minimum length to 60 characters
	validates :user, :post, presence: true
	# relationships
	belongs_to :user
	belongs_to :post
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /admin/comments
  # GET /admin/comments.json
  def index
    @comments = Admin::Comment.all
  end

  # GET /admin/comments/1
  # GET /admin/comments/1.json
  def show
  end

  # GET /admin/comments/new
  def new
    @comment = Admin::Comment.new
  end

  # GET /admin/comments/1/edit
  def edit
  end

  # POST /admin/comments
  # POST /admin/comments.json
  def create
    @comment = Admin::Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/comments/1
  # PATCH/PUT /admin/comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/comments/1
  # DELETE /admin/comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Admin::Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:admin_comment).permit(:Text, :Date, :Allowed, :author_id, :post_id)
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
	<% if @comment.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@comment.errors.count, "error") %> prohibited this admin_comment from being saved:</h2>

		<ul>
		<% @comment.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :Text %><br>
		<%= f.text_area :Text %>
	</div>

	<div class="field">
		<%= f.label :Date %><br>
		<%= f.date_select :Date %>
	</div>

	<div class="field">
		<%= f.label :Allowed %><br>
		<%= f.text_field :Allowed %>
	</div>

	<div class="field">
		<%= f.label :author_id %><br>
		<%= f.number_field :author_id %>
	</div>

	<div class="field">
		<%= f.label :post_id %><br>
		<%= f.number_field :post_id %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Editing Admin Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment, class: 'Button' %>
<%= link_to 'Back', admin_comments_path, class: 'Button' %>

app/views/admin/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Comments</h1>

<table>
	<thead>
		<tr>
			<th>Text</th>
			<th>Date</th>
			<th>Allowed</th>
			<th>Author</th>
			<th>Post</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
	<% @comments.each do |comment| %>
		<tr>
			<td><%= comment.Text %></td>
			<td><%= comment.Date %></td>
			<td><%= comment.Allowed %></td>
			<td><%= comment.user || 1 %></td>
			<td><%= comment.post || 1 %></td>
			<td><%= link_to 'Show', comment, class: 'Button' %></td>
			<td><%= link_to 'Edit', edit_admin_comment_path(comment), class: 'Button' %></td>
			<td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'Button' %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Comment', new_admin_comment_path, class: 'Button' %>

app/views/admin/comments/new.html.erb
<h1>New Admin Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_comments_path, class: 'Button' %>

app/views/admin/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Text:</strong>
	<%= @comment.Text %>
</p>

<p>
	<strong>Date:</strong>
	<%= @comment.Date %>
</p>

<p>
	<strong>Allowed:</strong>
	<%= @comment.Allowed %>
</p>

<p>
	<strong>Author:</strong>
	<%= @comment.author_id %>
</p>

<p>
	<strong>Post:</strong>
	<%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_admin_comment_path(@comment), class: 'Button' %> |
<%= link_to 'Back', admin_comments_path, class: 'Button' %>