config/routes.rb
Rails.application.routes.draw do
	root 'pages#index'

	get '/posts', to: 'pages#posts', as: 'posts'
	get '/post/:id', to: 'pages#post', as: 'post'

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	get '/admin', to: 'admin#index'
	namespace :admin do
		resources :posts
		resources :categories
		resources :users
		resources :privileges
		resources :comments
	end

end

app/models/admin.rb
module Admin
end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
	# validations
	validates :Title, presence: true
	# relationship
	has_many :posts
	has_one :category
	belongs_to :category

	def to_s
		"#{self.Title}"
	end
end

app/models/admin/comment.rb
class Admin::Comment < ActiveRecord::Base
	# validations
	validates :Text, length: {minimum: 60}      # set minimum length to 60 characters
	validates :user, :post, presence: true
	# relationships
	belongs_to :user
	belongs_to :post
end

app/models/admin/post.rb
class Admin::Post < ActiveRecord::Base
	validates :Title, :Date, :user, :category, presence: true
	# relationships
	belongs_to :user
	belongs_to :category
	has_many :comments

	def to_s
		"#{self.id}"
	end
end

app/models/admin/privilege.rb
class Admin::Privilege < ActiveRecord::Base
	has_one :user
end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
	# validations
	before_validation 'align_privileges'
	validates :Name, :Surname, :Email, :Group, :privilege, presence: true
	validates :Email, uniqueness: true
	# settings
	has_secure_password     # secure passwords for our users

	enum Group: {user: 0, admin: 1, root: 2}
	# relationship
	belongs_to :privilege
	has_many :posts, dependent: :destroy
	has_many :comments

	def Group=(value)
		if value.kind_of?(String) and value.to_i.to_s == value
			super value.to_i
		else
			super value
		end
	end

	def to_s
		"#{self.Nickname}"
	end

	def check_privilege(privilege)
		self.privilege[privilege]
	end

	private
	def align_privileges
		unless self.privilege.nil?
			return
		end
		if self.user?
			self.privilege = Admin::Privilege.find(3)
		elsif self.admin?
			self.privilege = Admin::Privilege.find(2)
		elsif self.root?
			self.privilege = Admin::Privilege.find(1)
		end
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	# permissions checks
	before_action only: [:show, :new, :edit] { check_permission :EditPosts }
	before_action only: [:destroy] { check_permission :DeletePosts }

	# GET /admin/posts
	# GET /admin/posts.json
	def index
		@posts = Admin::Post.all.reverse_order
	end

	# GET /admin/posts/1
	# GET /admin/posts/1.json
	def show
	end

	# GET /admin/posts/new
	def new
		@post = Admin::Post.new
	end

	# GET /admin/posts/1/edit
	def edit
	end

	# POST /admin/posts
	# POST /admin/posts.json
	def create
		@post = Admin::Post.new(post_params)

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
				format.json { render :show, status: :created, location: @post }
			else
				format.html { render :new }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /admin/posts/1
	# PATCH/PUT /admin/posts/1.json
	def update
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
				format.json { render :show, status: :ok, location: @post }
			else
				format.html { render :edit }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /admin/posts/1
	# DELETE /admin/posts/1.json
	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_post
		@post = Admin::Post.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def post_params
		params.require(:admin_post).permit(:Title, :Image, :Text, :Date, :user_id, :category_id, :Published)
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin_application'
  #before_action 'allowed?'

  def index
  end

  private
  def allowed?
    unless current_user.admin? or current_user.root?
      redirect_to root_path
    end
  end

  def check_permission(permission)
    unless current_user.check_privilege permission
      redirect_to admin_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@posts = Admin::Post.where({Published: true}).last(5).reverse
	end

	def posts
		@posts = Admin::Post.where({Published: true}).last(20).reverse
	end

	def post
		@post = Admin::Post.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			raise ActionController::RoutingError.new "#{params[:id]} does not direct to a record"
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'session_application'

  def new
  end

  def create
    @user = Admin::User.find_by(Nickname: params[:session]['Nickname'])
    if @user and @user.authenticate params[:session]['Password']
      log_in @user
      redirect_to root_path
    else
      flash.now['Error'] = 'Invalid login/password'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/privileges_helper.rb
module Admin::PrivilegesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def siteName
		Rails.configuration.x.site['site_name']
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= Admin::User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.clear
		@current_user = nil
	end
end

app/views/admin/_navigation.html.erb
<header>
	<nav role="navigation">
		<%= link_to root_path, class: 'item' do %>
			<span class="fa fa-home"></span> <%= siteName %>
		<% end %>
		<%= link_to admin_user_path(current_user), class: 'item' do %>
			<span class="fa fa-user"></span> Profile
		<% end %>

		<span class="Separator"></span>

		<%= link_to admin_path, class: 'item' do %>
			<span class="fa fa-dashboard"></span> Dashboard
		<% end %>
		<%= link_to admin_posts_path, class: 'item' do %>
			<span class="fa fa-file"></span> Posts
		<% end %>
		<%= link_to admin_comments_path, class: 'item' do %>
			<span class="fa fa-comment"></span> Comments
		<% end %>
		<%= link_to admin_categories_path, class: 'item' do %>
			<span class="fa fa-object-group"></span> Categories
		<% end %>
		<% if current_user.check_privilege :EditUsers %>
			<%= link_to admin_users_path, class: 'item' do %>
				<span class="fa fa-users"></span> Users
			<% end %>
		<% else %>
		<% end %>
		<% if current_user.check_privilege :EditPrivileges %>
			<%= link_to admin_privileges_path, class: 'item' do %>
				<span class="fa fa-unlock"></span> Privileges
			<% end %>
		<% end %>
	</nav>
</header>

app/views/admin/index.html.erb
<h1>Dashboard</h1>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= siteName %></title>

	<% unless params[:controller].eql? 'admin' %>
		<%= stylesheet_link_tag params[:controller], media: 'all' %>
	<% end %>
	<%= stylesheet_link_tag 'admin', media: 'all' %>
	<%= stylesheet_link_tag 'scaffolds', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'><!-- font -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"><!-- icons -->
	<%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'admin/navigation' %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= siteName %></title>
	<%= stylesheet_link_tag params[:controller] %>

	<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'><!-- font -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"><!-- icons -->

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'navigation' %>

<%= yield %>

<%# render partial: 'footer' %>

<script type="text/javascript" data-turbolinks-track="true">
	var reformalOptions = {
		project_id: 973009,
		project_host: "controlit.reformal.ru",
		tab_orientation: "bottom-left",
		tab_indent: "10px",
		tab_bg_color: "#5f5f5f",
		tab_border_color: "#FFFFFF",
		tab_image_url: "http://tab.reformal.ru/T9GC0LfRi9Cy0Ysg0Lgg0L%252FRgNC10LTQu9C%252B0LbQtdC90LjRjw==/FFFFFF/9c1f751cd883e990123aab292c606f93/bottom-left/1/tab.png",
		tab_border_width: 0
	};

	(function() {
		var script = document.createElement('script');
		script.type = 'text/javascript'; script.async = true;
		script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'media.reformal.ru/widgets/v3/reformal.js';
		document.getElementsByTagName('head')[0].appendChild(script);
	})();
</script><noscript><a href="http://reformal.ru"><img src="http://media.reformal.ru/reformal.png" /></a><a href="http://controlit.reformal.ru">Oтзывы и предложения для controlit</a></noscript>

</body>
</html>

app/views/layouts/session_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site title</title>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'><!-- font -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"><!-- icons -->
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash['Error'] %>
    <div><%= flash['Error'] %></div>
<% end %>
<%= yield %>


</body>
</html>

app/views/pages/_footer.html.erb
<footer>

  <div class="Group">
    <div class="Title"><h3>Widget_last posts (example)</h3></div>

    <% 2.times do %>
        <div class="WidgetPosts">
          <img src="http://placehold.it/80x80">
          <a>Super puper title! It should not be very long or it will be truncated as in current example. That's not the end yet. Wait for it, wait for it. Just wait a minute or two and then check again.</a>
        </div>
    <% end %>

  </div>
  <div class="Group">
    <div class="Title"><h3>Widget_text (example)</h3></div>

    <p>TrendyBlog is a professional HTML5 template perfect for newspaper publishers, magazines ort personal blogs.

      You get 30 fully featured pages with lots of widgets, menus, different post layouts and homepages.</p>
    <p>TrendyBlog is a professional HTML5 template perfect for newspaper publishers, magazines ort personal blogs.

      You get 30 fully featured pages with lots of widgets, menus, different post layouts and homepages.</p>


  </div>
  <div class="Group">
    <div class="Title"><h3>Widget_last posts (example)</h3></div>

    <% 2.times do %>
        <div class="WidgetPosts">
          <img src="http://placehold.it/80x80">
          <a>Super puper title! It should not be very long or it will be truncated as in current example. </a>
        </div>
    <% end %>

  </div>

</footer>

app/views/pages/_navigation.html.erb
<header>
	<nav role="navigation">
		<%= link_to root_path, class: 'item' do %>
			<span class="fa fa-home fa-lg"></span> <%= siteName %>
		<% end %>
		<%= link_to translate('Posts'), posts_path, class: 'item' %>
		<% unless logged_in? %>
		<%= link_to translate('Log_in'), login_path, class: 'item' %>
		<% else %>
		<% if current_user.admin? or current_user.root? %>
		<%= link_to translate('Dashboard'), admin_path, class: 'item' %>
		<% end %>
		<%= link_to translate('Log_out'), logout_path, method: 'delete', class: 'item' %>
		<% end %>
	</nav>
</header>

app/views/pages/_post_preview.html.erb
<% if type.eql? 'narrow' %>
<div class="PostPreviewNarrow">
	<div class="Thumbnail">
		<img src="<%= post_preview.Image || 'http://placehold.it/200' %>">
	</div>

	<h3><%= post_preview.Title %></h3>
	<p>Nam in pharetra nulla. Cras aliquet feugiat sapien a dictum. Sed ullamcorper, erat eu cursus sollicitudin, lorem orci condimentum ante.</p>
</div>

<% elsif type.eql? 'wide' %>
	<div class="PostPreviewWide Stretch">
		<img src="<%= post_preview.Image || 'http://placehold.it/200x150' %>" align="left">
	    <div class="Content">
			<h2><%= link_to post_preview.Title, post_path(post_preview)%></h2>
			<div><%= post_preview.Text.truncate(300).html_safe %></div>
		</div>
    </div>
<% end %>

app/views/pages/index.html.erb
<div class="FlexContainer" id="Body">
  <div id="Content" style="order: 0;">

	<div class="Group" style="display: none">
	  <div class="Title"><h4>Featured</h4></div>

	<div class="FlexContainer">
		<!-- First big block -->
		<%= render partial: 'post_preview', collection: @posts, locals: {type: 'narrow'} %>
		<!-- end of first big block -->
	  </div>

	</div>

    <div class="Group">
      <div class="Title"><h1><%= translate 'Latest' %></h1></div>

      <div class="FlexContainer Stretch" style="flex-direction: column;">
		<%= render partial: 'post_preview', collection: @posts, locals: { type: 'wide'} %>
      </div>
    </div>

  </div>
  <!-- end of Content -->
  <!-- Sidebar -->
  <div id="Sidebar" style="order: 1; display: none;">

    <div class="Group">
      <div class="Title"><h2>Widget_last posts (example)</h2></div>

      <% 4.times do %>
      <div class="WidgetPosts">
        <a>Super puper title! It should not be very long or it will be truncated as in current example. That's not the end yet. Wait for it, wait for it. Just wait a minute or two and then check again.</a>
      </div>
      <% end %>

    </div>

  </div>
  <!-- end of sidebar -->
</div>
<!-- end of body content -->

app/views/pages/post.html.erb
<div id="Body" class="FlexContainer">
  <!-- content -->
  <div id="Content">
	<h1><%= @post.Title %></h1>
    <%= @post.Text.html_safe %>

    <div class="Group" style="display: none;">
      <div class="Title"><h4>Related posts</h4></div>

      <div class="FlexContainer">

        <% 3.times do %>
            <div class="PostPreviewNarrow">
              <div class="Thumbnail">
                <img src="http://placehold.it/500x300">
              </div>
              <h3>Very interesting, 100%!</h3>
            </div>
        <% end %>
      </div>
    </div>

  </div>

  <!-- sidebar -->
  <div id="Sidebar" style="display: none;">
    <div class="Group">
      <div class="Title"><h3>Widget_last posts (example)</h3></div>

      <% 4.times do %>
          <div class="WidgetPosts">
            <img src="http://placehold.it/80x80">
            <a>Super puper title! It should not be very long or it will be truncated as in current example. That's not the end yet. Wait for it, wait for it. Just wait a minute or two and then check again.</a>
          </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/posts.html.erb
<div id="Body" class="FlexContainer">
	<!-- content -->
	<div id="Content">

	<div class="Group">
		<div class="Title"><h1><%= translate('Latest') %></h1></div>

		<div class="FlexContainer Stretch" style="flex-direction: column">
			<%= render partial: 'post_preview', collection: @posts , locals: { type: 'wide' }%>
		</div>
	</div>

	</div>

	<!-- sidebar -->
	<div id="Sidebar" style="display: none;">
	<div class="Group">
	  <div class="Title"><h3>Widget_last posts (example)</h3></div>

	  <% 4.times do %>
	      <div class="WidgetPosts">
	        <img src="http://placehold.it/80x80">
	        <a>Super puper title! It should not be very long or it will be truncated as in current example. That's not
	          the end yet. Wait for it, wait for it. Just wait a minute or two and then check again.</a>
	      </div>
	  <% end %>

	</div>
	</div>
</div>