config/routes.rb
Rails.application.routes.draw do
	root 'pages#index'

	get '/posts', to: 'pages#posts', as: 'posts'
	get '/post/:id', to: 'pages#post', as: 'post'

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	get '/admin', to: 'admin#index'
	namespace :admin do
		resources :posts
		resources :categories
		resources :users
		resources :privileges
		resources :comments
	end

end

app/models/admin/post.rb
class Admin::Post < ActiveRecord::Base
	validates :Title, :Date, :user, :category, presence: true
	# relationships
	belongs_to :user
	belongs_to :category
	has_many :comments

	def to_s
		"#{self.id}"
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	# permissions checks
	before_action only: [:show, :new, :edit] { check_permission :EditPosts }
	before_action only: [:destroy] { check_permission :DeletePosts }

	# GET /admin/posts
	# GET /admin/posts.json
	def index
		@posts = Admin::Post.all.reverse_order
	end

	# GET /admin/posts/1
	# GET /admin/posts/1.json
	def show
	end

	# GET /admin/posts/new
	def new
		@post = Admin::Post.new
	end

	# GET /admin/posts/1/edit
	def edit
	end

	# POST /admin/posts
	# POST /admin/posts.json
	def create
		@post = Admin::Post.new(post_params)

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
				format.json { render :show, status: :created, location: @post }
			else
				format.html { render :new }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /admin/posts/1
	# PATCH/PUT /admin/posts/1.json
	def update
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
				format.json { render :show, status: :ok, location: @post }
			else
				format.html { render :edit }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /admin/posts/1
	# DELETE /admin/posts/1.json
	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_post
		@post = Admin::Post.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def post_params
		params.require(:admin_post).permit(:Title, :Image, :Text, :Date, :user_id, :category_id, :Published)
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for(@post) do |f| %>
	<% if @post.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

		<ul>
		<% @post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :Title %><br>
		<%= f.text_field :Title %>
	</div>

	<div class="field">
		<%= f.label :Text %><br>
		<%= f.text_area :Text, id: 'editor' %>
	</div>

    <div class="field">
      <%= f.label :Image %><br>
      <%= f.text_field :Image%>
    </div>

	<div class="field">
		<%= f.label :Date %><br>
		<%= f.date_select :Date %>
	</div>

	<div class="field">
		<%= f.label :user_id %><br>
		<%= f.select :user_id, Admin::User.all.collect {|p| [p.Nickname, p.id]} %>
	</div>

	<div class="field">
		<%= f.label :category_id %><br>
		<%= f.select :category_id, Admin::Category.all.collect {|p| [p.Title, p.id]} %>
	</div>

	<div class="field">
		<%= f.label :Published %><br>
		<%= f.check_box :Published %>
	</div>

	<div class="actions">
	<%= f.submit %>
	</div>
<% end %>

<script src="//cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script>
<script>CKEDITOR.replace('editor');</script>

app/views/admin/posts/edit.html.erb
<h1>Editing Admin Post</h1>

<%= link_to 'Preview', post_path(@post), target: '_blank' %>

<%= render 'form' %>

<%= link_to 'Show', @post, class: 'Button' %>
<%= link_to 'Back', admin_posts_path, class: 'Button' %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Posts</h1>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Thumbnail</th>
			<th>Text</th>
			<th>Date</th>
			<th>Author</th>
			<th>Category</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
	<% @posts.each do |post| %>
		<tr style="background-color: <% if post.Published %>lightgreen<% else %>lightpink<% end %>;">
			<td><%= post.Title %></td>
			<td><img src="<%= post.Image %>" height="64px" width="80px"></td>
			<td><%= post.Text.truncate(300).html_safe %></td>
			<td><%= post.Date %></td>
			<td><%= post.user %></td>
			<td><%= post.category %></td>
			<td id="nb"><%= link_to 'Show', post, class: 'Button' %></td>
			<td id="nb"><%= link_to 'Edit', edit_admin_post_path(post), class: 'Button' %></td>
			<td id="nb"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'Button' %></td>
		</tr>
	<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Post', new_admin_post_path, class: 'Button' %>

app/views/admin/posts/new.html.erb
<h1>New Admin Post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @post.Title %>
</p>

<p>
	<strong>Image:</strong>
	<%= @post.Image %>
</p>

<p>
	<strong>Text:</strong>
	<%= @post.Text %>
</p>

<p>
	<strong>Date:</strong>
	<%= @post.Date %>
</p>

<p>
	<strong>Author:</strong>
	<%= @post.user %>
</p>

<p>
	<strong>Category:</strong>
	<%= @post.category %>
</p>

<p>
	<strong>Published: </strong><%= @post.Published? %>
</p>

<%= link_to 'Edit', edit_admin_post_path(@post), class: 'Button' %>
<%= link_to 'Back', admin_posts_path, class: 'Button' %>