config/routes.rb
Rails.application.routes.draw do
	root 'pages#index'

	get '/posts', to: 'pages#posts', as: 'posts'
	get '/post/:id', to: 'pages#post', as: 'post'

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	get '/admin', to: 'admin#index'
	namespace :admin do
		resources :posts
		resources :categories
		resources :users
		resources :privileges
		resources :comments
	end

end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
	# validations
	before_validation 'align_privileges'
	validates :Name, :Surname, :Email, :Group, :privilege, presence: true
	validates :Email, uniqueness: true
	# settings
	has_secure_password     # secure passwords for our users

	enum Group: {user: 0, admin: 1, root: 2}
	# relationship
	belongs_to :privilege
	has_many :posts, dependent: :destroy
	has_many :comments

	def Group=(value)
		if value.kind_of?(String) and value.to_i.to_s == value
			super value.to_i
		else
			super value
		end
	end

	def to_s
		"#{self.Nickname}"
	end

	def check_privilege(privilege)
		self.privilege[privilege]
	end

	private
	def align_privileges
		unless self.privilege.nil?
			return
		end
		if self.user?
			self.privilege = Admin::Privilege.find(3)
		elsif self.admin?
			self.privilege = Admin::Privilege.find(2)
		elsif self.root?
			self.privilege = Admin::Privilege.find(1)
		end
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	# GET /admin/users
	# GET /admin/users.json
	def index
		@users = Admin::User.all
	end

	# GET /admin/users/1
	# GET /admin/users/1.json
	def show
	end

	# GET /admin/users/new
	def new
		@user = Admin::User.new
	end

	# GET /admin/users/1/edit
	def edit
	end

	# POST /admin/users
	# POST /admin/users.json
	def create
		@user = Admin::User.new(user_params)

		respond_to do |format|
			if @user.save
				format.html { redirect_to @user, notice: 'User was successfully created.' }
				format.json { render :show, status: :created, location: @user }
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /admin/users/1
	# PATCH/PUT /admin/users/1.json
	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /admin/users/1
	# DELETE /admin/users/1.json
	def destroy
		@user.destroy
		respond_to do |format|
			format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = Admin::User.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
		params.require(:admin_user).permit(:Nickname, :Name, :Surname, :Email, :Group, :password, :password_confirmation)
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
	
		<ul>
		<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	</div>
	<% end %>
	
	<div class="field">
		<%= f.label :Nickname %><br>
		<%= f.text_field :Nickname %>
	</div>
	
	<div class="field">
		<%= f.label :Name %><br>
		<%= f.text_field :Name %>
	</div>
	
	<div class="field">
		<%= f.label :Surname %><br>
		<%= f.text_field :Surname %>
	</div>

	<div class="field">
		<%= f.label :Email %><br>
		<%= f.text_field :Email %>
	</div>

	<div class="field">
		<%= f.label :Group %><br>
		<%= f.select :Group, Admin::User.Groups, selected: Admin::User.Groups[@user.Group] %>
	</div>
	
	<div class="field">
		<%= f.label :password %><br>
		<%= f.text_field :password %>
	</div>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.text_field :password_confirmation %>
    </div>
	
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: 'Button' %>
<%= link_to 'Back', admin_users_path, class: 'Button' %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Users</h1>

<table>
	<thead>
		<tr>
			<th>Nickname</th>
			<th>Name</th>
			<th>Surname</th>
			<th>Email</th>
			<th>Group</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.Nickname %></td>
				<td><%= user.Name %></td>
				<td><%= user.Surname %></td>
				<td><%= user.Email %></td>
				<td><%= user.Group %></td>
				<td><%= link_to 'Show', user, class: 'Button' %></td>
				<td><%= link_to 'Edit', edit_admin_user_path(user), class: 'Button' %></td>
				<td><%= link_to 'Destroy', user, method: 'delete', data: { confirm: 'Are you sure?' }, class: 'Button' %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path, class: 'Button' %>

app/views/admin/users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path, class: 'Button' %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nickname:</strong>
  <%= @user.Nickname %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.Name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.Surname %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user.Group %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user), class: 'Button' %>
<%= link_to 'Back', admin_users_path, class: 'Button' %>